### ISSUE TITLE
CD4+_Tcells

### ISSUE THREAD

**Issue by alead** [keyes-timothy/classes#3]
I looked over your differential abundance analysis. To confirm, CD4+_Tcells are not significantly enriched in PAP samples vs. nonPAP? I am surprised given this frequency chart where brown is CD4+_Tcells. How are you doing these comparisons? Are you comparing proportions of cells between tissue type? comparing number of cells per area (i.e. number of fovs)?

![image](https://user-images.githubusercontent.com/50126948/119423156-7dc48400-bcb7-11eb-97a8-797ffddc24cb.png)

**Comment by keyes-timothy** [comment]
@alead It looks like when you made this chart you collapsed across FOVs (and just found the proportion of each cell type in total across all FOVs collected for a given patient). I don't know if that approach is better or worse than the approach that I took, which treats each FOV separately and explicitly models the effect of individual FOVs sometimes coming from the same patient (this is what the "random effect" of patient_id means in the mixed model). 

The effect of "condition" (PAP vs. nonPAP) for CD4+ T-cells was not significant in the mixed model. There are details about this in the report, but this image might also help to clarify. 

![CD4_by_category](https://user-images.githubusercontent.com/11278186/119904317-06813100-beff-11eb-8cf3-76f2b1758ff9.png)

It looks like what's happening here is that there is one FOV from the pneumonia patient that actually has a pretty large number of T-cells, and because we have so few control FOVs, it's hard to be confident that the difference in CD4+ T-cells (which definitely seems to be the trend) is real because of that outlier. If we removed the outlier, the effect would probably become significant, but then I'm also led to wonder if we removed outliers fast-and-loose for other cell types, would we be cherry-picking the data to fit our hypotheses?

**Comment by alead** [comment]
Can you plot this as combining normal and pneumonia into a nonPAP category? Then do the statistical test?

Also what is the y axis? Number of cells?

**Comment by alead** [comment]
Also, (I changed this in my figure), each "patient_id" is actually sample_id. They are different because 1 patient has 4 samples and the rest have 1 sample, so technically there are 9 SJIA-PAP patients, not 12 (this is my bad)

**Comment by keyes-timothy** [comment]
The statistics are the same regardless of how I plot them. The mixed models were fit with Normal and Pneumonia combined into a single category (I visualize them separately here for illustrative purposes).

**Comment by keyes-timothy** [comment]
And yes the axis is number of CD4+ T-cells.

**Comment by alead** [comment]
For your plot, do you normalize by number of FOVs?

**Comment by keyes-timothy** [comment]
Each point is an FOV.

**Comment by alead** [comment]
Ok makes sense
